name: Build libtcc
on: workflow_dispatch

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build libtcc
        run: |
          git clone https://repo.or.cz/tinycc.git
          cd tinycc
          ./configure --enable-shared --disable-static
          make
          
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: libtcc-linux
          path: tinycc/libtcc.so
